// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/login": {
            "post": {
                "description": "login user to get jwt token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Login User.",
                "parameters": [
                    {
                        "description": "JSON username and user_pass",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.SuccessLoginUser"
                        }
                    },
                    "401": {
                        "description": "unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.FailCreateUser"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "$ref": "#/definitions/model.FailCreateUser"
                        }
                    }
                }
            }
        },
        "/register": {
            "post": {
                "description": "create new user with username, user_email. user_pass.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Create/Register New User.",
                "parameters": [
                    {
                        "description": "JSON username, user_email, and user_pass",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.CreateUser"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.CreateUser"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.FailCreateUser"
                        }
                    }
                }
            }
        },
        "/{username}": {
            "get": {
                "description": "get a user information by username.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Get a User.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Username",
                        "name": "username",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "$ref": "#/definitions/model.UserFound"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.JWTNotFound"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/model.UserNotFound"
                        }
                    }
                }
            }
        },
        "/{username}/activities": {
            "get": {
                "description": "get all activity by user.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Activity"
                ],
                "summary": "Get All Activity.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Username",
                        "name": "username",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Activity"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.JWTNotFound"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/model.UserNotFound"
                        }
                    }
                }
            },
            "post": {
                "description": "create new activity for user.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Activity"
                ],
                "summary": "Create New Activity.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Username",
                        "name": "username",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "JSON",
                        "name": "activity",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.CreateActivity"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.CreateActivity"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.JWTNotFound"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/model.UserNotFound"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.FailCreateActivity"
                        }
                    }
                }
            }
        },
        "/{username}/activities/archives": {
            "get": {
                "description": "get all archived activity by user.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Activity"
                ],
                "summary": "Get All Archived Activity.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Username",
                        "name": "username",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Activity"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.JWTNotFound"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/model.UserNotFound"
                        }
                    }
                }
            }
        },
        "/{username}/activities/{activity_name}": {
            "get": {
                "description": "get a activity by activity name.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Activity"
                ],
                "summary": "Get a Activity.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Username",
                        "name": "username",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Activity Name",
                        "name": "activity_name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Activity"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.JWTNotFound"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.NoAccess"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/model.ActivityNotFound"
                        }
                    }
                }
            },
            "put": {
                "description": "update a activity by activity name.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Activity"
                ],
                "summary": "Update a Activity.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Username",
                        "name": "username",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Activity Name",
                        "name": "activity_name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "JSON",
                        "name": "activity",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.CreateActivity"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.ActivityUpdated"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.JWTNotFound"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.NoAccess"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/model.FailUpdateActivity"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a activity by activity name.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Activity"
                ],
                "summary": "Delete a Activity.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Username",
                        "name": "username",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Activity Name",
                        "name": "activity_name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.ActivityDeleted"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.JWTNotFound"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.NoAccessOwner"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/model.ActivityNotFound"
                        }
                    }
                }
            }
        },
        "/{username}/activities/{activity_name}/archive": {
            "put": {
                "description": "archive a activity by activity name.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Activity"
                ],
                "summary": "Archive a Activity.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Username",
                        "name": "username",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Activity Name",
                        "name": "activity_name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.ActivityArchived"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.JWTNotFound"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.NoAccessOwner"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/model.FailUpdateActivity"
                        }
                    }
                }
            },
            "delete": {
                "description": "restore a activity by activity name.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Activity"
                ],
                "summary": "Restore a Activity.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Username",
                        "name": "username",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Activity Name",
                        "name": "activity_name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.ActivityRestored"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.JWTNotFound"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.NoAccessOwner"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/model.FailUpdateActivity"
                        }
                    }
                }
            }
        },
        "/{username}/activities/{activity_name}/manage": {
            "get": {
                "description": "get list access user to activity.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Access"
                ],
                "summary": "Get List Access User to Activity.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Username",
                        "name": "username",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Activity Name",
                        "name": "activity_name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.ListAccess"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.JWTNotFound"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.NoAccessOwner"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/model.ActivityNotFound"
                        }
                    }
                }
            },
            "post": {
                "description": "add access user to activity.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Access"
                ],
                "summary": "Add Access User to Activity.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Username",
                        "name": "username",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Activity Name",
                        "name": "activity_name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "JSON",
                        "name": "access",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.CreateAccess"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.SuccessCreateAccess"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.AddYourself"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.NoAccessOwner"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/model.ActivityNotFound"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.FailCreateAccess"
                        }
                    }
                }
            },
            "delete": {
                "description": "delete access another user to activity.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Access"
                ],
                "summary": "Delete Access Another User to Activity.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Username",
                        "name": "username",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Activity Name",
                        "name": "activity_name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "JSON",
                        "name": "access",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.CreateAccess"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.SuccessDeleteAccess"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.JWTNotFound"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.NoAccessOwner"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/model.FailDeleteAccess"
                        }
                    }
                }
            }
        },
        "/{username}/activities/{activity_name}/remove": {
            "delete": {
                "description": "remove access user from activity.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Access"
                ],
                "summary": "Remove Access User from Activity.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Username",
                        "name": "username",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Activity Name",
                        "name": "activity_name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.SuccessRemoveAccess"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.JWTNotFound"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.NoAccessOwner"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/model.FailDeleteAccess"
                        }
                    }
                }
            }
        },
        "/{username}/activities/{activity_name}/tasks": {
            "get": {
                "description": "get all task in an activity.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Task"
                ],
                "summary": "Get All Task in an Activity.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Username",
                        "name": "username",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Activity Name",
                        "name": "activity_name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Task"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.JWTNotFound"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.NoAccess"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/model.ActivityNotFound"
                        }
                    }
                }
            },
            "post": {
                "description": "create task of an activity.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Task"
                ],
                "summary": "Create Task of an Activity.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Username",
                        "name": "username",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Activity Name",
                        "name": "activity_name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "JSON",
                        "name": "task",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.CreateTask"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.SuccessCreateTask"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.JWTNotFound"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.NoAccess"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/model.ActivityNotFound"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.FailCreateTask"
                        }
                    }
                }
            }
        },
        "/{username}/activities/{activity_name}/tasks/{id}": {
            "get": {
                "description": "get a task in an activity.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Task"
                ],
                "summary": "Get a Task in an Activity.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Username",
                        "name": "username",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Activity Name",
                        "name": "activity_name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID task",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Task"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.JWTNotFound"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.NoAccess"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/model.TaskNotFound"
                        }
                    }
                }
            },
            "put": {
                "description": "update a task in an activity.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Task"
                ],
                "summary": "Update a Task in an Activity.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Username",
                        "name": "username",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Activity Name",
                        "name": "activity_name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID task",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "JSON",
                        "name": "task",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.CreateTask"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.TaskUpdated"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.JWTNotFound"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.NoAccess"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/model.FailUpdateTask"
                        }
                    }
                }
            },
            "delete": {
                "description": "delete a task in an activity.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Task"
                ],
                "summary": "Delete a Task in an Activity.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Username",
                        "name": "username",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Activity Name",
                        "name": "activity_name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID task",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.TaskDeleted"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.JWTNotFound"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.NoAccess"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/model.FailUpdateTask"
                        }
                    }
                }
            }
        },
        "/{username}/activities/{activity_name}/tasks/{id}/complete": {
            "put": {
                "description": "complete a task in an activity.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Task"
                ],
                "summary": "Complete a Task in an Activity.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Username",
                        "name": "username",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Activity Name",
                        "name": "activity_name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID task",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.TaskCompleted"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.JWTNotFound"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.NoAccess"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/model.TaskNotFound"
                        }
                    }
                }
            },
            "delete": {
                "description": "undo a completed task in an activity.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Task"
                ],
                "summary": "Undo a Completed Task in an Activity.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Username",
                        "name": "username",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Activity Name",
                        "name": "activity_name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID task",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.TaskUndo"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.JWTNotFound"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.NoAccess"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/model.TaskNotFound"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "gorm.DeletedAt": {
            "type": "object",
            "properties": {
                "time": {
                    "type": "string"
                },
                "valid": {
                    "description": "Valid is true if Time is not NULL",
                    "type": "boolean"
                }
            }
        },
        "model.Access": {
            "type": "object",
            "properties": {
                "access_owner": {
                    "type": "boolean"
                },
                "activity_id": {
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "id": {
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "model.Activity": {
            "type": "object",
            "properties": {
                "Tasks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Task"
                    }
                },
                "accesses": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Access"
                    }
                },
                "activity_name": {
                    "type": "string"
                },
                "archived": {
                    "type": "boolean"
                },
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "id": {
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "model.ActivityArchived": {
            "type": "object",
            "properties": {
                "messages": {
                    "type": "string",
                    "example": "activity archived"
                }
            }
        },
        "model.ActivityDeleted": {
            "type": "object",
            "properties": {
                "messages": {
                    "type": "string",
                    "example": "activity deleted"
                }
            }
        },
        "model.ActivityNotFound": {
            "type": "object",
            "properties": {
                "messages": {
                    "type": "string",
                    "example": "activity not found"
                }
            }
        },
        "model.ActivityRestored": {
            "type": "object",
            "properties": {
                "messages": {
                    "type": "string",
                    "example": "activity is restored"
                }
            }
        },
        "model.ActivityUpdated": {
            "type": "object",
            "properties": {
                "activity_name": {
                    "type": "string",
                    "example": "Kegiatan 1"
                },
                "messages": {
                    "type": "string",
                    "example": "activity edited"
                }
            }
        },
        "model.AddYourself": {
            "type": "object",
            "properties": {
                "messages": {
                    "type": "string",
                    "example": "can't add yourself"
                }
            }
        },
        "model.CreateAccess": {
            "type": "object",
            "properties": {
                "username": {
                    "type": "string",
                    "example": "arifwidiasan"
                }
            }
        },
        "model.CreateActivity": {
            "type": "object",
            "properties": {
                "activity_name": {
                    "type": "string",
                    "example": "Kegiatan 1"
                }
            }
        },
        "model.CreateTask": {
            "type": "object",
            "properties": {
                "task_name": {
                    "type": "string",
                    "example": "buat dokumentasi"
                },
                "task_priority": {
                    "type": "string",
                    "example": "1"
                }
            }
        },
        "model.CreateUser": {
            "type": "object",
            "properties": {
                "user_email": {
                    "type": "string",
                    "example": "arifw.subagio17@gmail.com"
                },
                "user_pass": {
                    "type": "string",
                    "example": "rahasia87"
                },
                "username": {
                    "type": "string",
                    "example": "arifwidiasan"
                }
            }
        },
        "model.FailCreateAccess": {
            "type": "object",
            "properties": {
                "messages": {
                    "type": "string",
                    "example": "error insert access"
                }
            }
        },
        "model.FailCreateActivity": {
            "type": "object",
            "properties": {
                "messages": {
                    "type": "string",
                    "example": "error insert activity"
                }
            }
        },
        "model.FailCreateTask": {
            "type": "object",
            "properties": {
                "messages": {
                    "type": "string",
                    "example": "error insert task"
                }
            }
        },
        "model.FailCreateUser": {
            "type": "object",
            "properties": {
                "messages": {
                    "type": "string",
                    "example": "error insert user"
                }
            }
        },
        "model.FailDeleteAccess": {
            "type": "object",
            "properties": {
                "messages": {
                    "type": "string",
                    "example": "error delete because you're the owner or no access found"
                }
            }
        },
        "model.FailUpdateActivity": {
            "type": "object",
            "properties": {
                "messages": {
                    "type": "string",
                    "example": "no id found or no change"
                }
            }
        },
        "model.FailUpdateTask": {
            "type": "object",
            "properties": {
                "messages": {
                    "type": "string",
                    "example": "task not found or no change"
                }
            }
        },
        "model.JWTNotFound": {
            "type": "object",
            "properties": {
                "messages": {
                    "type": "string",
                    "example": "missing or malformed jwt"
                }
            }
        },
        "model.ListAccess": {
            "type": "object",
            "properties": {
                "access_Owner": {
                    "type": "boolean",
                    "example": true
                },
                "username": {
                    "type": "string",
                    "example": "arifwidiasan"
                }
            }
        },
        "model.LoginRequest": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string",
                    "example": "rahasia87"
                },
                "username": {
                    "type": "string",
                    "example": "arifwidiasan"
                }
            }
        },
        "model.NoAccess": {
            "type": "object",
            "properties": {
                "messages": {
                    "type": "string",
                    "example": "you have no access to this activity"
                }
            }
        },
        "model.NoAccessOwner": {
            "type": "object",
            "properties": {
                "messages": {
                    "type": "string",
                    "example": "you dont have access to this activity or not owner"
                }
            }
        },
        "model.SuccessCreateAccess": {
            "type": "object",
            "properties": {
                "activity_name": {
                    "type": "string",
                    "example": "Kegiatan 1"
                },
                "messages": {
                    "type": "string",
                    "example": "success add another user to this activity"
                },
                "username": {
                    "type": "string",
                    "example": "arifwidiasan"
                }
            }
        },
        "model.SuccessCreateTask": {
            "type": "object",
            "properties": {
                "activity_name": {
                    "type": "string",
                    "example": "Kegiatan 1"
                },
                "messages": {
                    "type": "string",
                    "example": "success add task to this activity"
                },
                "task_name": {
                    "type": "string",
                    "example": "buat dokumentasi"
                }
            }
        },
        "model.SuccessDeleteAccess": {
            "type": "object",
            "properties": {
                "activity_name": {
                    "type": "string",
                    "example": "Kegiatan 1"
                },
                "messages": {
                    "type": "string",
                    "example": "success delete user to this activity"
                },
                "username": {
                    "type": "string",
                    "example": "arifwidiasan"
                }
            }
        },
        "model.SuccessLoginUser": {
            "type": "object",
            "properties": {
                "messages": {
                    "type": "string",
                    "example": "success"
                },
                "token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NTI3ODI1OTIsImlkIjoxLCJ1c2VybmFtZSI6ImFyaWZ3aWRpYXNhbiJ9.Cve64349wPdD4HALRWnLqTzH4ByN20SRT_Zw-Vmrrm4"
                }
            }
        },
        "model.SuccessRemoveAccess": {
            "type": "object",
            "properties": {
                "activity_name": {
                    "type": "string",
                    "example": "Kegiatan 1"
                },
                "messages": {
                    "type": "string",
                    "example": "success delete access, you can't access this activity anymore"
                }
            }
        },
        "model.Task": {
            "type": "object",
            "properties": {
                "activity_id": {
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "id": {
                    "type": "integer"
                },
                "task_done": {
                    "type": "boolean"
                },
                "task_name": {
                    "type": "string"
                },
                "task_priority": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "model.TaskCompleted": {
            "type": "object",
            "properties": {
                "messages": {
                    "type": "string",
                    "example": "task completed"
                },
                "tasks": {
                    "$ref": "#/definitions/model.Task"
                }
            }
        },
        "model.TaskDeleted": {
            "type": "object",
            "properties": {
                "messages": {
                    "type": "string",
                    "example": "task deleted"
                }
            }
        },
        "model.TaskNotFound": {
            "type": "object",
            "properties": {
                "messages": {
                    "type": "string",
                    "example": "task not found"
                }
            }
        },
        "model.TaskUndo": {
            "type": "object",
            "properties": {
                "messages": {
                    "type": "string",
                    "example": "success undo completed task"
                },
                "tasks": {
                    "$ref": "#/definitions/model.Task"
                }
            }
        },
        "model.TaskUpdated": {
            "type": "object",
            "properties": {
                "messages": {
                    "type": "string",
                    "example": "success update task"
                },
                "tasks": {
                    "$ref": "#/definitions/model.Task"
                }
            }
        },
        "model.UserFound": {
            "type": "object",
            "properties": {
                "user_email": {
                    "type": "string",
                    "example": "arifw.subagio17@gmail.com"
                },
                "user_pass": {
                    "type": "string",
                    "example": "rahasia87"
                },
                "username": {
                    "type": "string",
                    "example": "arifwidiasan"
                }
            }
        },
        "model.UserNotFound": {
            "type": "object",
            "properties": {
                "messages": {
                    "type": "string",
                    "example": "username not found"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.0",
	Host:             "localhost:8080",
	BasePath:         "/v1",
	Schemes:          []string{"http"},
	Title:            "To-do List App API",
	Description:      "Documentation of To-do List App API.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
