basePath: /v1
definitions:
  docs.CreateAccess:
    properties:
      username:
        example: arifwidiasan
        type: string
    type: object
  docs.CreateActivity:
    properties:
      activity_name:
        example: Kegiatan 1
        type: string
    type: object
  docs.CreateTask:
    properties:
      task_name:
        example: buat dokumentasi
        type: string
      task_priority:
        example: "1"
        type: string
    type: object
  docs.CreateUser:
    properties:
      user_email:
        example: arifw.subagio17@gmail.com
        type: string
      user_pass:
        example: rahasia87
        type: string
      username:
        example: arifwidiasan
        type: string
    type: object
  model.ListAccess:
    properties:
      access_owner:
        example: true
        type: boolean
      username:
        example: arifwidiasan
        type: string
    type: object
  model.LoginRequest:
    properties:
      password:
        example: rahasia87
        type: string
      username:
        example: arifwidiasan
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: Documentation of To-do List App API.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: To-do List App API
  version: "2.0"
paths:
  /:
    get:
      consumes:
      - application/json
      description: get a user information by username.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "404":
          description: error not found
          schema:
            type: string
      summary: Get a User.
      tags:
      - User
  /activities:
    get:
      consumes:
      - application/json
      description: get all activity by user.
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
        "400":
          description: bad request
          schema:
            type: string
        "404":
          description: not found
          schema:
            type: string
      summary: Get All Activity.
      tags:
      - Activity
    post:
      consumes:
      - application/json
      description: create new activity for user.
      parameters:
      - description: JSON
        in: body
        name: activity
        required: true
        schema:
          $ref: '#/definitions/docs.CreateActivity'
      produces:
      - application/json
      responses:
        "201":
          description: created
          schema:
            type: string
        "400":
          description: bad request
          schema:
            type: string
        "404":
          description: not found
          schema:
            type: string
        "500":
          description: internal server error
          schema:
            type: string
      summary: Create New Activity.
      tags:
      - Activity
  /activities/{activity_name}:
    delete:
      consumes:
      - application/json
      description: Delete a activity by activity name.
      parameters:
      - description: Activity Name
        in: path
        name: activity_name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
        "400":
          description: bad request
          schema:
            type: string
        "401":
          description: no access
          schema:
            type: string
        "404":
          description: not found
          schema:
            type: string
      summary: Delete a Activity.
      tags:
      - Activity
    get:
      consumes:
      - application/json
      description: get a activity by activity name.
      parameters:
      - description: Activity Name
        in: path
        name: activity_name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
        "400":
          description: bad request
          schema:
            type: string
        "401":
          description: no access
          schema:
            type: string
        "404":
          description: not found
          schema:
            type: string
      summary: Get a Activity.
      tags:
      - Activity
    put:
      consumes:
      - application/json
      description: update a activity by activity name.
      parameters:
      - description: Activity Name
        in: path
        name: activity_name
        required: true
        type: string
      - description: JSON
        in: body
        name: activity
        required: true
        schema:
          $ref: '#/definitions/docs.CreateActivity'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
        "400":
          description: bad request
          schema:
            type: string
        "401":
          description: no access
          schema:
            type: string
        "404":
          description: not found
          schema:
            type: string
      summary: Update a Activity.
      tags:
      - Activity
  /activities/{activity_name}/archive:
    delete:
      consumes:
      - application/json
      description: restore a activity by activity name.
      parameters:
      - description: Activity Name
        in: path
        name: activity_name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
        "400":
          description: bad request
          schema:
            type: string
        "401":
          description: no access
          schema:
            type: string
        "404":
          description: not dound
          schema:
            type: string
      summary: Restore a Activity.
      tags:
      - Activity
    put:
      consumes:
      - application/json
      description: archive a activity by activity name.
      parameters:
      - description: Activity Name
        in: path
        name: activity_name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
        "400":
          description: bad request
          schema:
            type: string
        "401":
          description: no access
          schema:
            type: string
        "404":
          description: not found
          schema:
            type: string
      summary: Archive a Activity.
      tags:
      - Activity
  /activities/{activity_name}/manage:
    delete:
      consumes:
      - application/json
      description: delete access another user to activity.
      parameters:
      - description: Activity Name
        in: path
        name: activity_name
        required: true
        type: string
      - description: JSON
        in: body
        name: access
        required: true
        schema:
          $ref: '#/definitions/docs.CreateAccess'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
        "400":
          description: bad request
          schema:
            type: string
        "401":
          description: unauthorized
          schema:
            type: string
        "404":
          description: not found
          schema:
            type: string
      summary: Delete Access Another User to Activity.
      tags:
      - Access
    get:
      consumes:
      - application/json
      description: get list access user to activity.
      parameters:
      - description: Activity Name
        in: path
        name: activity_name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.ListAccess'
        "400":
          description: bad request
          schema:
            type: string
        "401":
          description: unauthorized
          schema:
            type: string
        "404":
          description: not found
          schema:
            type: string
      summary: Get List Access User to Activity.
      tags:
      - Access
    post:
      consumes:
      - application/json
      description: add access user to activity.
      parameters:
      - description: Activity Name
        in: path
        name: activity_name
        required: true
        type: string
      - description: JSON
        in: body
        name: access
        required: true
        schema:
          $ref: '#/definitions/docs.CreateAccess'
      produces:
      - application/json
      responses:
        "201":
          description: created
          schema:
            type: string
        "400":
          description: bad request
          schema:
            type: string
        "401":
          description: unauthorized
          schema:
            type: string
        "404":
          description: not found
          schema:
            type: string
        "500":
          description: internal server error
          schema:
            type: string
      summary: Add Access User to Activity.
      tags:
      - Access
  /activities/{activity_name}/remove:
    delete:
      consumes:
      - application/json
      description: remove access user from activity.
      parameters:
      - description: Activity Name
        in: path
        name: activity_name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
        "400":
          description: bad request
          schema:
            type: string
        "401":
          description: unauthorized
          schema:
            type: string
        "404":
          description: not found
          schema:
            type: string
      summary: Remove Access User from Activity.
      tags:
      - Access
  /activities/{activity_name}/tasks:
    get:
      consumes:
      - application/json
      description: get all task in an activity.
      parameters:
      - description: Activity Name
        in: path
        name: activity_name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
        "400":
          description: bad request
          schema:
            type: string
        "401":
          description: no access
          schema:
            type: string
        "404":
          description: not found
          schema:
            type: string
      summary: Get All Task in an Activity.
      tags:
      - Task
    post:
      consumes:
      - application/json
      description: create task of an activity.
      parameters:
      - description: Activity Name
        in: path
        name: activity_name
        required: true
        type: string
      - description: JSON
        in: body
        name: task
        required: true
        schema:
          $ref: '#/definitions/docs.CreateTask'
      produces:
      - application/json
      responses:
        "201":
          description: created
          schema:
            type: string
        "400":
          description: bad request
          schema:
            type: string
        "401":
          description: no access
          schema:
            type: string
        "404":
          description: not found
          schema:
            type: string
        "500":
          description: internal server error
          schema:
            type: string
      summary: Create Task of an Activity.
      tags:
      - Task
  /activities/{activity_name}/tasks/{id}:
    delete:
      consumes:
      - application/json
      description: delete a task in an activity.
      parameters:
      - description: Activity Name
        in: path
        name: activity_name
        required: true
        type: string
      - description: ID task
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
        "400":
          description: bad request
          schema:
            type: string
        "401":
          description: no access
          schema:
            type: string
        "404":
          description: not found
          schema:
            type: string
      summary: Delete a Task in an Activity.
      tags:
      - Task
    get:
      consumes:
      - application/json
      description: get a task in an activity.
      parameters:
      - description: Activity Name
        in: path
        name: activity_name
        required: true
        type: string
      - description: ID task
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
        "400":
          description: bad request
          schema:
            type: string
        "401":
          description: no access
          schema:
            type: string
        "404":
          description: not found
          schema:
            type: string
      summary: Get a Task in an Activity.
      tags:
      - Task
    put:
      consumes:
      - application/json
      description: update a task in an activity.
      parameters:
      - description: Activity Name
        in: path
        name: activity_name
        required: true
        type: string
      - description: ID task
        in: path
        name: id
        required: true
        type: string
      - description: JSON
        in: body
        name: task
        required: true
        schema:
          $ref: '#/definitions/docs.CreateTask'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
        "400":
          description: bad request
          schema:
            type: string
        "401":
          description: no access
          schema:
            type: string
        "404":
          description: not found
          schema:
            type: string
      summary: Update a Task in an Activity.
      tags:
      - Task
  /activities/{activity_name}/tasks/{id}/complete:
    delete:
      consumes:
      - application/json
      description: undo a completed task in an activity.
      parameters:
      - description: Activity Name
        in: path
        name: activity_name
        required: true
        type: string
      - description: ID task
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
        "400":
          description: bad request
          schema:
            type: string
        "401":
          description: no access
          schema:
            type: string
        "404":
          description: not found
          schema:
            type: string
      summary: Undo a Completed Task in an Activity.
      tags:
      - Task
    put:
      consumes:
      - application/json
      description: complete a task in an activity.
      parameters:
      - description: Activity Name
        in: path
        name: activity_name
        required: true
        type: string
      - description: ID task
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
        "400":
          description: bad request
          schema:
            type: string
        "401":
          description: no access
          schema:
            type: string
        "404":
          description: not found
          schema:
            type: string
      summary: Complete a Task in an Activity.
      tags:
      - Task
  /activities/archives:
    get:
      consumes:
      - application/json
      description: get all archived activity by user.
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
        "400":
          description: bad request
          schema:
            type: string
        "404":
          description: not found
          schema:
            type: string
      summary: Get All Archived Activity.
      tags:
      - Activity
  /login:
    post:
      consumes:
      - application/json
      description: login user to get jwt token.
      parameters:
      - description: JSON username and user_pass
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
        "401":
          description: unauthorized
          schema:
            type: string
        "500":
          description: internal server error
          schema:
            type: string
      summary: Login User.
      tags:
      - User
  /register:
    post:
      consumes:
      - application/json
      description: create new user with username, user_email. user_pass.
      parameters:
      - description: JSON username, user_email, and user_pass
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/docs.CreateUser'
      produces:
      - application/json
      responses:
        "201":
          description: created
          schema:
            type: string
        "500":
          description: error insert user
          schema:
            type: string
      summary: Create/Register New User.
      tags:
      - User
schemes:
- http
swagger: "2.0"
