name: Deploy
on:
  push:
    branches:
      - "master"
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: ec2 deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd todo-app
          git pull origin main
          go test -v ./..
          docker-compose down && docker-compose up --build -d